# Generated by Django 5.0.4 on 2024-06-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('primaryemail', models.EmailField(max_length=254)),
                ('secondaryemail', models.EmailField(max_length=254)),
                ('primarycontact', models.BigIntegerField()),
                ('secondarycontact', models.BigIntegerField()),
                ('contactperson', models.CharField(max_length=100)),
                ('customersegment', models.CharField(max_length=100)),
                ('shifttopartyaddress', models.CharField(max_length=100)),
                ('shifttopartycity', models.CharField(max_length=100)),
                ('shifttopartystate', models.CharField(max_length=100)),
                ('shifttopartypostal', models.CharField(max_length=100)),
                ('soldtopartyaddress', models.CharField(max_length=100)),
                ('soldtopartycity', models.CharField(max_length=100)),
                ('soldtopartystate', models.CharField(max_length=100)),
                ('soldtopartypostal', models.CharField(max_length=100)),
                ('customerid', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemnumber', models.IntegerField()),
                ('itemname', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modeofpayment', models.CharField(max_length=100)),
                ('dispatchedthrough', models.CharField(max_length=100)),
                ('termofdelivery', models.CharField(max_length=100)),
                ('termsandcondition', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='lead_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceoflead', models.CharField(max_length=100)),
                ('salesperson', models.CharField(max_length=100)),
                ('havedonepestcontrolearlier', models.CharField(max_length=100)),
                ('leadstatus', models.CharField(max_length=100)),
                ('typeofcontract', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(default='Unknown', max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('termsandcondition', models.CharField(max_length=200)),
                ('servicetype_q', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='service_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pestcontrolservice', models.CharField(max_length=100)),
                ('services', models.CharField(max_length=100)),
                ('servicetype', models.CharField(max_length=100)),
            ],
        ),
    ]
