# Generated by Django 5.1.1 on 2024-12-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='techworklist',
            name='payment_photo',
        ),
        migrations.RemoveField(
            model_name='techworklist',
            name='photo_after_service',
        ),
        migrations.RemoveField(
            model_name='techworklist',
            name='photo_before_service',
        ),
        migrations.AddField(
            model_name='techworklist',
            name='payment_photos',
            field=models.ManyToManyField(blank=True, related_name='payment_photos', to='crmapp.uploadedfile'),
        ),
        migrations.AddField(
            model_name='techworklist',
            name='photos_after_service',
            field=models.ManyToManyField(blank=True, related_name='photos_after_service', to='crmapp.uploadedfile'),
        ),
        migrations.AddField(
            model_name='techworklist',
            name='photos_before_service',
            field=models.ManyToManyField(blank=True, related_name='photos_before_service', to='crmapp.uploadedfile'),
        ),
    ]
