# Generated by Django 5.1.1 on 2024-12-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0004_service_management_delivery_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workallocation',
            old_name='customer_phone_number',
            new_name='customer_contact',
        ),
        migrations.RemoveField(
            model_name='workallocation',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='workallocation',
            name='customer_id',
            field=models.CharField(default='1', max_length=255),
        ),
    ]
