# Generated by Django 5.0.4 on 2024-06-19 10:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0004_remove_inventory_summary_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory_summary',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
