# Generated by Django 5.1.1 on 2024-12-12 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0005_rename_customer_phone_number_workallocation_customer_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workallocation',
            name='service',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='crmapp.service_management'),
        ),
    ]
