# Generated by Django 5.1.1 on 2024-12-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0006_workallocation_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workallocation',
            name='service',
        ),
        migrations.AddField(
            model_name='workallocation',
            name='gps_location',
            field=models.URLField(blank=True, null=True),
        ),
    ]
