# Generated by Django 5.0.4 on 2024-07-15 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0007_service_management_gst_checkbox_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_management',
            name='total_area_of_pest_control',
        ),
    ]
