# Generated by Django 5.1.1 on 2024-12-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0007_remove_workallocation_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workallocation',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='workallocation',
            name='customer_fname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workallocation',
            name='customer_lname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
