# Generated by Django 5.0.4 on 2024-07-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0008_remove_service_management_total_area_of_pest_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_management',
            name='payment_terms_checkbox',
            field=models.CharField(max_length=200),
        ),
    ]
