# Generated by Django 5.0.4 on 2024-07-15 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0009_alter_service_management_payment_terms_checkbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_management',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crmapp.customer_details'),
        ),
    ]
