# Generated by Django 5.0.4 on 2024-07-15 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0010_service_management_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_management',
            name='customer_full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='service_management',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmapp.customer_details'),
        ),
    ]
