# Generated by Django 5.0.4 on 2024-07-15 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0011_service_management_customer_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_management',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='service_management',
            name='customer_full_name',
        ),
    ]
