# Generated by Django 5.0.4 on 2024-07-16 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0012_remove_service_management_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_management',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crmapp.customer_details'),
        ),
    ]
