# Generated by Django 5.0.4 on 2024-07-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0013_service_management_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_management',
            name='gst_status',
            field=models.CharField(default='NON-GST', max_length=10),
        ),
    ]
