# Generated by Django 5.0.4 on 2024-07-17 06:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0014_service_management_gst_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='company_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='company_contact_no',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='quotation',
            name='company_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crmapp.customer_details'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='gst_checkbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotation',
            name='quotation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='quotation',
            name='subject',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='total_amount_with_gst',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='termsandcondition',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
