# Generated by Django 5.0.4 on 2024-07-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0015_quotation_company_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='servicetype_q',
            field=models.CharField(max_length=5000),
        ),
    ]
