# Generated by Django 5.0.4 on 2024-07-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0016_alter_quotation_servicetype_q'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='total_amount',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
