# Generated by Django 5.0.4 on 2024-07-18 09:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0017_alter_quotation_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='account_no',
            field=models.CharField(default='Null', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='branch',
            field=models.CharField(default='Null', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='company_contact_no',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='company_email',
            field=models.EmailField(default='Null', max_length=254),
        ),
        migrations.AddField(
            model_name='invoice',
            name='company_name',
            field=models.CharField(default='Null', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crmapp.customer_details'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='invoice',
            name='delivery_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='invoice',
            name='description_of_goods',
            field=models.TextField(default='Null', max_length=5000),
        ),
        migrations.AddField(
            model_name='invoice',
            name='designation',
            field=models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], default='Null', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='dispatched_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='invoice',
            name='gst_checkbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='hsn_sac_code',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ifsc_code',
            field=models.CharField(default='Null', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pan_card_no',
            field=models.CharField(default='Null', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_amount',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_amount_in_words',
            field=models.CharField(default='', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_amount_with_gst',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='dispatchedthrough',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='modeofpayment',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='termofdelivery',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='termsandcondition',
            field=models.CharField(default='Null', max_length=255),
        ),
    ]
