# Generated by Django 5.0.4 on 2024-07-20 06:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0018_invoice_account_no_invoice_branch_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='inventory',
        ),
        migrations.AddField(
            model_name='lead_management',
            name='contactno',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lead_management',
            name='customeraddress',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead_management',
            name='customeremail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='lead_management',
            name='dateoflead',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lead_management',
            name='leadstatus',
            field=models.CharField(choices=[('Call', 'Call'), ('Visit', 'Visit'), ('Quotation', 'Quotation')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lead_management',
            name='typeofcontract',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly')], max_length=100),
        ),
    ]
