# Generated by Django 5.0.4 on 2024-07-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0019_delete_inventory_lead_management_contactno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead_management',
            name='visitorsname',
            field=models.CharField(default='Null', max_length=200),
        ),
    ]
