# Generated by Django 5.0.4 on 2024-08-05 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0021_technicianprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicianprofile',
            name='specialization',
        ),
    ]
