# Generated by Django 5.0.4 on 2024-08-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0022_remove_technicianprofile_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianprofile',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='password',
            field=models.CharField(default='none', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
