# Generated by Django 5.0.4 on 2024-08-05 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0023_technicianprofile_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicianprofile',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='technicianprofile',
            name='password',
        ),
    ]
