# Generated by Django 5.0.4 on 2024-08-06 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0024_remove_technicianprofile_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianprofile',
            name='password',
            field=models.CharField(default='none', max_length=128),
            preserve_default=False,
        ),
    ]
