# Generated by Django 5.0.4 on 2024-08-06 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models



def set_default_user(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    TechnicianProfile = apps.get_model('crmapp', 'TechnicianProfile')

    # Set a default user if needed
    default_user = User.objects.first()  # Get a default user or handle appropriately
    if default_user:
        TechnicianProfile.objects.update(user=default_user)

class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0025_technicianprofile_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianprofile',
            name='user',
            field=models.OneToOneField(to='auth.User', on_delete=models.CASCADE, default=None),
            preserve_default=False,
        ),
        migrations.RunPython(set_default_user),
    ]
