# Generated by Django 5.0.4 on 2024-08-06 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0029_remove_technicianprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TechnicianProfile',
        ),
    ]
