# Generated by Django 5.0.4 on 2024-08-06 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0039_alter_technicianprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone_number', models.CharField(max_length=15)),
                ('customer_address', models.CharField(max_length=255)),
                ('work_description', models.TextField()),
                ('customer_payment_status', models.CharField(max_length=50)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmapp.technicianprofile')),
            ],
        ),
    ]
