# Generated by Django 5.0.4 on 2024-08-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0041_alter_technicianprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workallocation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
