# Generated by Django 5.0.4 on 2024-08-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0043_techworklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='techworklist',
            name='completion_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
