# Generated by Django 5.0.4 on 2024-10-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0046_workallocation_allocated_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Pest Control', 'Pest Control'), ('Fumigation', 'Fumigation'), ('Product Sell', 'Product Sell')], default='NULL', max_length=50),
        ),
    ]
