# Generated by Django 5.0.4 on 2024-10-15 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0048_remove_service_management_pestcontrolservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_management',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='service_management',
            name='gst_checkbox',
        ),
        migrations.RemoveField(
            model_name='service_management',
            name='gst_status',
        ),
        migrations.RemoveField(
            model_name='service_management',
            name='lead_date',
        ),
        migrations.RemoveField(
            model_name='service_management',
            name='payment_terms_checkbox',
        ),
        migrations.RemoveField(
            model_name='service_management',
            name='sales_person_contact_no',
        ),
        migrations.RemoveField(
            model_name='service_management',
            name='sales_person_name',
        ),
        migrations.RemoveField(
            model_name='service_management',
            name='service_charges',
        ),
        migrations.RemoveField(
            model_name='service_management',
            name='service_date',
        ),
        migrations.RemoveField(
            model_name='service_management',
            name='service_frequency',
        ),
        migrations.RemoveField(
            model_name='service_management',
            name='servicetype',
        ),
        migrations.RemoveField(
            model_name='service_management',
            name='technician_operator_name',
        ),
        migrations.RemoveField(
            model_name='service_management',
            name='total_charges',
        ),
    ]
