# Generated by Django 5.0.4 on 2024-10-15 01:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0049_remove_service_management_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_management',
            name='address',
            field=models.TextField(default='Null'),
        ),
        migrations.AddField(
            model_name='service_management',
            name='city',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='service_management',
            name='contract_status',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Not selected', 'No selected')], default='NOT SELECTED', max_length=100),
        ),
        migrations.AddField(
            model_name='service_management',
            name='contract_type',
            field=models.CharField(choices=[('One Time', 'One Time'), ('AMC', 'AMC'), ('Warranty', 'Warranty')], default='NOT SELECTED', max_length=50),
        ),
        migrations.AddField(
            model_name='service_management',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crmapp.customer_details'),
        ),
        migrations.AddField(
            model_name='service_management',
            name='frequency_count',
            field=models.CharField(choices=[('1-12', '1-12'), ('Fortnight', 'Fortnight'), ('Weekly', 'Weekly'), ('Daily', 'Daily')], default='NOT SELECTED', max_length=50),
        ),
        migrations.AddField(
            model_name='service_management',
            name='gps_location',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service_management',
            name='gst_checkbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service_management',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='service_management',
            name='gst_status',
            field=models.CharField(default='NON-GST', max_length=10),
        ),
        migrations.AddField(
            model_name='service_management',
            name='lead_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='service_management',
            name='payment_terms',
            field=models.CharField(default='100% Advance payment OR Whatever mutually Decided', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='service_management',
            name='pincode',
            field=models.CharField(default=0, max_length=6),
        ),
        migrations.AddField(
            model_name='service_management',
            name='property_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service_management',
            name='sales_person_contact_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='service_management',
            name='sales_person_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service_management',
            name='service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service_management',
            name='servicetype',
            field=models.CharField(choices=[('Pest Control', 'Pest Control'), ('Fumigation', 'Fumigation'), ('Product Sell', 'Product Sell')], default='Pest Control', max_length=100),
        ),
        migrations.AddField(
            model_name='service_management',
            name='state',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='service_management',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service_management',
            name='total_price_with_gst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service_management',
            name='warranty_period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='service_management',
            name='services',
        ),
        migrations.AddField(
            model_name='service_management',
            name='services',
            field=models.ManyToManyField(to='crmapp.product'),
        ),
    ]
