# Generated by Django 5.0.4 on 2024-10-15 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0050_service_management_address_service_management_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_management',
            name='total_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
