# Generated by Django 5.0.4 on 2024-10-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0051_service_management_total_charges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_management',
            name='customer',
        ),
        migrations.AddField(
            model_name='service_management',
            name='customer_contact',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='service_management',
            name='customer_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='service_management',
            name='customer_name',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AlterField(
            model_name='service_management',
            name='contract_status',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='NOT SELECTED', max_length=100),
        ),
    ]
