# Generated by Django 5.0.4 on 2024-10-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0053_alter_service_management_frequency_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_management',
            name='servicetype',
            field=models.CharField(choices=[('Pest Control', 'Pest Control'), ('Fumigation', 'Fumigation'), ('Product Sell', 'Product Sell')], max_length=100),
        ),
    ]
